require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe DeliveryMethodsController do

  # This should return the minimal set of attributes required to create a valid
  # DeliveryMethod. As you add validations to DeliveryMethod, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "user" => "" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # DeliveryMethodsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all delivery_methods as @delivery_methods" do
      delivery_method = DeliveryMethod.create! valid_attributes
      get :index, {}, valid_session
      assigns(:delivery_methods).should eq([delivery_method])
    end
  end

  describe "GET show" do
    it "assigns the requested delivery_method as @delivery_method" do
      delivery_method = DeliveryMethod.create! valid_attributes
      get :show, {:id => delivery_method.to_param}, valid_session
      assigns(:delivery_method).should eq(delivery_method)
    end
  end

  describe "GET new" do
    it "assigns a new delivery_method as @delivery_method" do
      get :new, {}, valid_session
      assigns(:delivery_method).should be_a_new(DeliveryMethod)
    end
  end

  describe "GET edit" do
    it "assigns the requested delivery_method as @delivery_method" do
      delivery_method = DeliveryMethod.create! valid_attributes
      get :edit, {:id => delivery_method.to_param}, valid_session
      assigns(:delivery_method).should eq(delivery_method)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new DeliveryMethod" do
        expect {
          post :create, {:delivery_method => valid_attributes}, valid_session
        }.to change(DeliveryMethod, :count).by(1)
      end

      it "assigns a newly created delivery_method as @delivery_method" do
        post :create, {:delivery_method => valid_attributes}, valid_session
        assigns(:delivery_method).should be_a(DeliveryMethod)
        assigns(:delivery_method).should be_persisted
      end

      it "redirects to the created delivery_method" do
        post :create, {:delivery_method => valid_attributes}, valid_session
        response.should redirect_to(DeliveryMethod.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved delivery_method as @delivery_method" do
        # Trigger the behavior that occurs when invalid params are submitted
        DeliveryMethod.any_instance.stub(:save).and_return(false)
        post :create, {:delivery_method => { "user" => "invalid value" }}, valid_session
        assigns(:delivery_method).should be_a_new(DeliveryMethod)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        DeliveryMethod.any_instance.stub(:save).and_return(false)
        post :create, {:delivery_method => { "user" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested delivery_method" do
        delivery_method = DeliveryMethod.create! valid_attributes
        # Assuming there are no other delivery_methods in the database, this
        # specifies that the DeliveryMethod created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        DeliveryMethod.any_instance.should_receive(:update).with({ "user" => "" })
        put :update, {:id => delivery_method.to_param, :delivery_method => { "user" => "" }}, valid_session
      end

      it "assigns the requested delivery_method as @delivery_method" do
        delivery_method = DeliveryMethod.create! valid_attributes
        put :update, {:id => delivery_method.to_param, :delivery_method => valid_attributes}, valid_session
        assigns(:delivery_method).should eq(delivery_method)
      end

      it "redirects to the delivery_method" do
        delivery_method = DeliveryMethod.create! valid_attributes
        put :update, {:id => delivery_method.to_param, :delivery_method => valid_attributes}, valid_session
        response.should redirect_to(delivery_method)
      end
    end

    describe "with invalid params" do
      it "assigns the delivery_method as @delivery_method" do
        delivery_method = DeliveryMethod.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        DeliveryMethod.any_instance.stub(:save).and_return(false)
        put :update, {:id => delivery_method.to_param, :delivery_method => { "user" => "invalid value" }}, valid_session
        assigns(:delivery_method).should eq(delivery_method)
      end

      it "re-renders the 'edit' template" do
        delivery_method = DeliveryMethod.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        DeliveryMethod.any_instance.stub(:save).and_return(false)
        put :update, {:id => delivery_method.to_param, :delivery_method => { "user" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested delivery_method" do
      delivery_method = DeliveryMethod.create! valid_attributes
      expect {
        delete :destroy, {:id => delivery_method.to_param}, valid_session
      }.to change(DeliveryMethod, :count).by(-1)
    end

    it "redirects to the delivery_methods list" do
      delivery_method = DeliveryMethod.create! valid_attributes
      delete :destroy, {:id => delivery_method.to_param}, valid_session
      response.should redirect_to(delivery_methods_url)
    end
  end

end
